### ISSUE TITLE
Why is every term of the loss function reduced by 2 in the proposed method?

### ISSUE THREAD

**Issue by aki916** [sair-lab/iMTSP#1]
https://github.com/sair-lab/iMTSP/blob/c17ff89413b65e085f04189ec9113d13175381b8/my_train.py#L40-L42

Would it be possible to tell me the reason why every term of the loss function is reduced by 2 in the proposed method?
Thanks in advance.

**Comment by gyf23205** [comment]
Hi,
The constant 2 is just for better visualization. If you stare at the loss for a while, you will notice that it's not necessarily positive since log_prob is always negative. To make the loss curve look normal (starting from a positive number and gradually covering to zero), we subtract an empirical upper bound (2 here) of the cost.
